### ISSUE TITLE
Always use nullable pandas backend 

### ISSUE THREAD

**Issue by hombit** [astronomy-commons/hipscat-import#231] opened 2024-02-21 15:32 UTC
Currently, all nulls in the input CSV data are implicitly converted to the corresponding NA value for a given type, such as NaN for floats. Users may change this with the following code:

```python
CsvReader(
    parquet_kwargs={
        'dtype_backend': 'numpy_nullable', # or 'pyarrow'
    }
)
```

However, it seems like a reasonable default behavior would be to always use one of the nullable dtype backends. "pyarrow" might be more preferable due to its better compatibility with Parquet.

Related to issue #227.

**Comment by nevencaplar** [comment] 2024-02-21 17:11
When you say ``nulls in the input CVS data'' - does that mean that zeros in the CVS, e.g., 0.0 gets read as NaN?

**Comment by hombit** [comment] 2024-02-21 19:27
@nevencaplar it is about missed / masked / NA / NULL values in the data. For example, in Gaia DR3 has some "null" (string literal) meaning missing value.

Currently, if the column dtype is float/double, `hipscat-import` would represent these values as float NaN, not parquet masked value. It is semantically different from the original data, but it still could be a reasonable thing to go with. However, it would not work with integers, because pandas (for a good reason) doesn't define NA value for integers.

This is one of the reasons why the current hipscated Gaia (created in #221) has a lot of wrong dtypes, using floats instead of integers. Implementing #225 will fix it for the special case of ECSV and Gaia, but would not be enough for arbitrary textual data with NULL values.

The proof that nullable dtype backends help with type guessing:
```python
In [18]: from io import StringIO
    ...: import pandas as pd
    ...:
    ...: csv = 'a,b\n1.0,null\nnull,1'
    ...: print(pd.read_csv(StringIO(csv)).dtypes)
    ...: print(pd.read_csv(StringIO(csv), dtype_backend='numpy_nullable').dtypes)
    ...: print(pd.read_csv(StringIO(csv), dtype_backend='pyarrow').dtypes)
a    float64
b    float64
dtype: object
a    Float64
b      Int64
dtype: object
a    double[pyarrow]
b     int64[pyarrow]
dtype: object
```

**Comment by nevencaplar** [comment] 2024-02-21 19:57
Thank you! I talked with @delucchi-cmu as well and it is much clearer now. Most of the confusion arose because I misinterpreted what ``nulls'' means.

**Comment by delucchi-cmu** [comment] 2024-03-12 12:43
I've played around with this some more, and I'm not happy with any of the approaches I've tried so far. 

Part of the problem is that you can't say `dtype_backend=None` to ignore the type-forcing behavior.  Once we set this value, users can't get back their simple datatypes, and they're forced into numpy or pyarrow behavior. The pandas documentation says that `numpy_nullable` is default, but there is different behavior when you don't set it at all and when you explicitly use `numpy_nullable`. Which is frustrating, but I'm not sure how to work around this in a way that users would be happy with.

**Comment by delucchi-cmu** [comment] 2024-03-12 13:05
For now, let's go ahead with the cleanup in #245, but otherwise close this issue.

**Closed as completed by delucchi-cmu** 2024-03-12 13:05 UTC
